### ISSUE TITLE
PHP Notice: Use of undefined constant - assumed ''

### ISSUE THREAD

**Issue by amatzon** [passatgt/wc-szamlazz#1]
PHP notice a `wp_szamlazz.php` fajlban, az alabbi sorokban: #162, #180, #192, #195. A sorok torlese es ujrairasa megoldja a problemat. Pull request?

**Comment by passatgt** [comment]
Már van v1.0.12, amiben többek között ez is javítva lett, hamarosan felrakom(még a héten)

Egyébként egy rejtett karakter van a sorok végén, az nem tetszik neki.

**Comment by passatgt** [comment]
Felkerült az 1.0.12
