### ISSUE TITLE
Áfa kulcs beallitasa

### ISSUE THREAD

**Issue by americaexpress** [passatgt/wc-szamlazz#5]
Szia!

Gyors segitseg kellene az afa kulcs bellitasahoz mert nekunk sehogy se sikerult!
A szamlazz.hu annyit mondott higy ezt mindenkepp a webshopba kell beallitani es nem naluk!
Tehat van egy olyan afa kulcs hogy AAM, hol es mikent tudjuk ezt beallitani az automatikus szamlageneralasbal??
Varom mielobbi valaszod!

Attila

**Comment by xstormy** [comment]
Szia!

Nekem is ez lenne a kérdésem, hogyan lehetne AAM-et beállítani mint ÁFA kulcs?

Köszönöm!

**Comment by passatgt** [comment]
@xstormy https://wordpress.org/support/topic/afamentesseg-beallitasa/
