### ISSUE TITLE
Alanyi Áfamentesség

### ISSUE THREAD

**Issue by sunikem** [passatgt/wc-szamlazz#6]
Kedves Péter, segítségre van szükségünk. A szamlaz.hu oldalon adták meg az elérhetőségedet. Telepítettük az általad készített plugint, amely a woocommerce  automatikus számlakiállításával kapcsolatos. A kérdés, hogyan lehet beállítani azt, hogy minden **automatikusan kiállított és elküldött** számla alanyi adómentes azaz AAM legyen, mivel a vállalkozásunk Áfa mentes. Várjuk válaszod.

**Comment by passatgt** [comment]
https://wordpress.org/support/topic/afamentesseg-beallitasa/
